version: '3.9'

services:
  api-1: &api1
    image: rinha-backend-2025:0.1
    container_name: api-1
    networks:
      - backend-rinha
      - payment-processor
    ports:
      - "9999:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=prod
      - HTTPCLIENT_CONNECTION_TIMEOUT=5000
      - HTTPCLIENT_READ_TIMEOUT=10000
      - HTTPCLIENT_SOCKET_TIMEOUT=10000
      - HTTPCLIENT_MAX_TOTAL_CONNECTIONS=400
      - HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS=400
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_URL=http://redis:6379
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
#          cpus: "0.6"
#          memory: "150MB"
          cpus: "1.5"
          memory: "400MB"

  redis:
    image: redis:8.0.3-alpine3.21
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend-rinha
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
#      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "15MB"

networks:
  backend-rinha:
    driver: bridge
  payment-processor:
    external: true