version: '3.9'

services:
  redis:
    image: redis:8.0.3-alpine3.21
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend-rinha
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128MB"

networks:
  backend-rinha:
    driver: bridge