services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
      - backend-02
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "50MB"
#          cpus: "1.5"
#          memory: "1150MB"

  backend-01: &backend
    image: rinha-backend-2025:0.2
    #image: docker.io/library/rinha-backend-2025-lecosas:0.0.1-SNAPSHOT
    container_name: backend-01
    hostname: backend-01
    networks:
      - backend
      - payment-processor
#    ports:
#      - "9998:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=prod
      - PAYMENT_BACKEND_MAIN_INSTANCE=true
      - PAYMENT_BACKEND_WORKER_FALLBACK_DELAY=10
      - HTTPCLIENT_CONNECTION_TIMEOUT=5000
      - HTTPCLIENT_READ_TIMEOUT=10000
      - HTTPCLIENT_SOCKET_TIMEOUT=10000
      - HTTPCLIENT_MAX_TOTAL_CONNECTIONS=1000
      - HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS=1000
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: "0.65"
          memory: "160MB"
#          cpus: "2.7"
#          memory: "3200MB"

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02
    environment:
      - PAYMENT_BACKEND_MAIN_INSTANCE=false
      - PAYMENT_BACKEND_WORKER_FALLBACK_DELAY=10
      - HTTPCLIENT_CONNECTION_TIMEOUT=5000
      - HTTPCLIENT_READ_TIMEOUT=10000
      - HTTPCLIENT_SOCKET_TIMEOUT=10000
      - HTTPCLIENT_MAX_TOTAL_CONNECTIONS=1000
      - HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS=1000
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:7-alpine
    container_name: redis
    command: redis-server --save "" --appendonly no --maxmemory 20Mb --maxmemory-policy allkeys-lru --tcp-keepalive 60 --timeout 0
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB" #Change in command line too.

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true