FROM vegardit/graalvm-maven:latest-java24 as builder

WORKDIR /app

COPY . .

RUN ./mvnw -Pnative native:compile -DskipTests

FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y zlib1g && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=builder /app/target/rinha-backend-2025-java-spring-graalvm app

EXPOSE 8080

CMD ["./app"]