FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y zlib1g && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/rinha-backend-2025-java-spring-graalvm app

EXPOSE 8080

CMD ["./app"]
