version: '3.9'

services:
  api-1: &api1
    image: rinha-backend-2025:0.1
    container_name: api-1
    networks:
      - backend-rinha
      - payment-processor
    ports:
      - "9999:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=prod
      - HTTPCLIENT_CONNECTION_TIMEOUT=5000
      - HTTPCLIENT_READ_TIMEOUT=10000
      - HTTPCLIENT_SOCKET_TIMEOUT=10000
      - HTTPCLIENT_MAX_TOTAL_CONNECTIONS=400
      - HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS=400
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "128MB"
        reservations:
          cpus: "0.6"
          memory: "128MB"

  redis:
    image: redis:8.0.3-alpine3.21
    container_name: redis
    command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend-rinha
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "128MB"

networks:
  backend-rinha:
    driver: bridge
  payment-processor:
    external: true