services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "9999:9999"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend-01
#        condition: service_healthy
      - backend-02
#        condition: service_healthy
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

  backend-01: &backend
    image: rinha-backend-2025:0.1
    container_name: backend-01
    hostname: backend-01
    networks:
      - backend
      - payment-processor
#    ports:
#      - "9998:8080"
    environment:
      #- SPRING_PROFILES_ACTIVE=prod
      - HTTPCLIENT_CONNECTION_TIMEOUT=5000
      - HTTPCLIENT_READ_TIMEOUT=10000
      - HTTPCLIENT_SOCKET_TIMEOUT=10000
      - HTTPCLIENT_MAX_TOTAL_CONNECTIONS=400
      - HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS=400
      - PAYMENT_PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      redis:
        condition: service_healthy
#    healthcheck:
#      test: "curl -f -s http://localhost:8080/actuator/health | grep UP || exit 1"
#      interval: 5s
#      timeout: 10s
#      retries: 3
#      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "160MB"

  backend-02:
    <<: *backend
    container_name: backend-02
    hostname: backend-02

  redis:
    image: redis:8.0.3-alpine3.21
    container_name: redis
    #command: redis-server --save "" --appendonly no --maxclients 20000
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
#      start_period: 5s
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "20MB"

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true