FROM ghcr.io/graalvm/native-image-community:24.0.2-ol8-20250715 as build

# Install necessary tools
RUN microdnf install wget
RUN microdnf install xz

# Install maven for build the spring boot application
RUN wget https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz
RUN tar xvf apache-maven-3.9.8-bin.tar.gz

# Set up the environment variables needed to run the Maven command.
ENV M2_HOME=/app/apache-maven-3.9.8
ENV M2=$M2_HOME/bin
ENV PATH=$M2:$PATH

# Install UPX (Ultimate Packer for eXecutables) to compress the executable binary and reduce its size.
RUN wget https://github.com/upx/upx/releases/download/v4.2.4/upx-4.2.4-amd64_linux.tar.xz
RUN tar xvf upx-4.2.4-amd64_linux.tar.xz

# Set up the environment variables required to run the UPX command.
ENV UPX_HOME=/app/upx-4.2.4-amd64_linux
ENV PATH=$UPX_HOME:$PATH

#Copy the spring boot source code into container
RUN mkdir -p /app
COPY . /app

#Compile the native image
RUN cd /app && mvn -Pnative native:compile

#Compressed binary file
RUN upx -7 -k /app/target/app-native-binary
WORKDIR /app

#Second stage: Create the runtime image
FROM arm64v8/alpine:3.22

#Set the working directory
WORKDIR /app

#Copy the built application from the first stage
COPY --from=build /app/target/app-native-binary .

#Expose port which our spring boot application is running
EXPOSE 8080

#Command to run the application
ENTRYPOINT ["/app/app-native-binary"]