httpclient:
  connection-timeout: ${HTTPCLIENT_CONNECTION_TIMEOUT:5000}
  read-timeout: ${HTTPCLIENT_READ_TIMEOUT:10000}
  socket-timeout: ${HTTPCLIENT_SOCKET_TIMEOUT:10000}
  max-total-connections: ${HTTPCLIENT_MAX_TOTAL_CONNECTIONS:400}
  max-per-route-connections: ${HTTPCLIENT_MAX_PER_ROUTE_CONNECTIONS:400}
  max-idle-time: ${HTTPCLIENT_MAX_IDLE_TIME:60000}
  max-life-time: ${HTTPCLIENT_MAX_LIFE_TIME:60000}

payment-backend:
  enqueue:
    delay: ${PAYMENT_BACKEND_ENQUEUE_DELAY:10}
  main-instance: ${PAYMENT_BACKEND_MAIN_INSTANCE:false}
  summary:
    delay-1: ${PAYMENT_BACKEND_SUMMARY_DELAY_1:20}
    delay-2: ${PAYMENT_BACKEND_SUMMARY_DELAY_2:10}
    delay-3: ${PAYMENT_BACKEND_SUMMARY_DELAY_3:20}
    delay-4: ${PAYMENT_BACKEND_SUMMARY_DELAY_4:10}
  warmup:
    cycles: ${PAYMENT_BACKEND_WARMUP_CYCLES:500}
  worker:
    count: ${PAYMENT_BACKEND_WORKER_COUNT:200}
    fallback-delay: ${PAYMENT_BACKEND_WORKER_FALLBACK_DELAY:50}
    thread-delay: ${PAYMENT_BACKEND_WORKER_THREAD_DELAY:2}
    paused-delay: ${PAYMENT_BACKEND_WORKER_PAUSED_DELAY:100}
    stopped-delay: ${PAYMENT_BACKEND_WORKER_STOPPED_DELAY:500}
    exception-delay: ${PAYMENT_BACKEND_WORKER_EXCEPTION_DELAY:500}

payment-processor:
  default-url: ${PAYMENT_PROCESSOR_DEFAULT_URL:http://localhost:8001}
  fallback-url: ${PAYMENT_PROCESSOR_FALLBACK_URL:http://localhost:8002}

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web.client.RestClient: DEBUG
#    org.apache.hc.client5.http: DEBUG
#    org.apache.hc.core5.http: DEBUG
#    org.apache.hc.core5.http.impl.io: DEBUG
#    org.apache.hc.client5.http.impl.classic: DEBUG
#    org.apache.hc.client5.http.wire: DEBUG

redis:
  url: redis://${REDIS_HOST:localhost}:${REDIS_PORT:6379}

server:
  ssl:
    enabled: false
  port: 8080
#  tomcat:
#    accesslog:
#      enabled: true
#    accept-count: 1000
    #    connection-timeout:
    #    keep-alive-timeout:
#    max-connections: 100
    #    max-http-form-post-size:
    #    max-http-response-header-size:
#    max-keep-alive-requests: 200
    #    processor-cache:
#    threads:
#      max: 1000 #default: 200 Doesn't have an effect if virtual threads are enabled.
#      #      max-queue-capacity: 2147483647 (default)
#      min-spare: 500 #default: 10 Doesn't have an effect if virtual threads are enabled.

spring:
  application:
    admin:
      enabled: false
    name: rinha-backend-2025-lecosas
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.admin.SpringApplicationAdminJmxAutoConfiguration
  main:
    banner-mode: off
  threads:
    virtual:
      enabled: ${JAVA_VIRTUAL_THREADS:true}